// LOCAL HOST //
### GET all Sales 
Get http://localhost:3000/sales

### Get Sales by id 
Get http://localhost:3000/sales/65b8fa4477f4551f5df6613c

### Create Sales 
Post http://localhost:3000/sales HTTP/1.1 
content-Type: application/json

{
   "carType": "Mazda",
    "location": "Gweru",
    "price": "$6 500",
    "color": "green",
    "condition": "new",
    "ownerGender": "female"
}
 
### Put sales
Put http://localhost:3000/sales/65c1233b3edef7a7cba83be6 HTTP/1.1 
content-Type: application/json

{
   "carType": "Mazda",
    "location": "Gweru",
    "price": "$6 500",
    "color": "green",
    "condition": "new",
    "ownerGender": "female"
}

### Delete sales 
DELETE http://localhost:3000/sales/65c1233b3edef7a7cba83be6 HTTP/1.1 
  
//PART TWO
// LOCAL HOST //
### GET all Clients 
Get http://localhost:3000/clients

### Get Clients by id 
Get http://localhost:3000/clients/65c06fc48a3bebdc8efa628c
### Create Clients 
Post http://localhost:3000/clients HTTP/1.1 
content-Type: application/json

{
   "customer": "Sam James",
    "sport": "soccer",
    "favoriteColor": "green",
    "purpose": "buy",
    "amount": "$200",
    "cases": "3",
    "date": "31 january 2021",
    "time": "1100hrs"
}

### Put Clients
Put http://localhost:3000/clients/65b94921f4f51374a46be3bc HTTP/1.1 
content-Type: application/json

{"customer": "Xavier Mhaka",
    "sport": "soccer",
    "favoriteColor": "green",
    "purpose": "buy",
    "amount": "$200",
    "cases": "3",
    "date": "31 january 2021",
    "time": "1100hrs"
}

### Delete Clients 
DELETE http://localhost:3000/clients/65c123993edef7a7cba83be7 HTTP/1.1 